### ISSUE TITLE
Add ⚠️ icon to breaking changes in release notes of 0.19.0

### ISSUE THREAD

**Issue by XiangRongLin** [charleskorn/kaml#138]
I was updating your library from 0.17.0 to 0.32.0 and just skimmed through your release notes in order to look for breaking changes. I saw that you marked them with ⚠️, so they were easy to find.
But for 0.19.0 you missed that, so i had to figure it out myself until i actually read the notes themselves.

I would find it very useful if you edited the release and added that icon

**Comment by charleskorn** [comment]
Thanks for the feedback @XiangRongLin, I've updated the release notes to better highlight breaking changes like you suggest.
