### ISSUE TITLE
Not all yaml equivalents for Boolean values are supported

### ISSUE THREAD

**Issue by BloodWorkXGaming** [charleskorn/kaml#150]
Looking through the sourcecode it seems like only a few of the boolean equivalents are supported.

The full List is here: https://yaml.org/type/bool.html

https://github.com/charleskorn/kaml/blob/2657221465168e85d2c810a58ef73f362679ed97/src/commonMain/kotlin/com/charleskorn/kaml/YamlNode.kt#L86-L87

**Comment by BloodWorkXGaming** [comment]
My bad, just found out that the spec I checked is only 1.1 not 1.2 which is lib is targeting.

Leaving this open for you to close and decide how to handle it.

**Comment by charleskorn** [comment]
Yep, this library targets YAML 1.2, and that defines the following as being allowed values for booleans ([source](https://yaml.org/spec/1.2/spec.html#id2805071)):

```
true | True | TRUE | false | False | FALSE
```
