### ISSUE TITLE
`kotlinx.serialization` should be exposed as `api`

### ISSUE THREAD

**Issue by MiSikora** [charleskorn/kaml#166]
`kaml` relies on `kotlinx.serialization` library in its public API and isn't usable without declaring an additional dependency on the artifact from the users.

https://github.com/charleskorn/kaml/blob/0890a9fedd1697c1e355a7e3455d00404385474b/build.gradle.kts#L56-L60

**Comment by charleskorn** [comment]
Good catch, thanks @MiSikora. I've fixed this and will push out an updated version shortly.
