### ISSUE TITLE
Support for option to serialize a List of strings to multi-line string in yaml output

### ISSUE THREAD

**Issue by bishwenduk029** [charleskorn/kaml#222]
### Describe the problem you'd like to solve

Support multi-line String serialization in yaml output for POJO -> List<String>. 

```data class POJO(examples: List<String>)```

allow to be serialized to below with pipe operator ( | )

```
examples: |
  - "Line 1 String"
  - "Line 2 String"
```

### Describe the solution you'd like

Currently we can use YamlConfiguration to control the output format of the yaml being produced from an object. If we can extend this YamlConfiguration to now also support setting a boolean flag which can be used to call

In YamlOutput

```kotlin
emitLiteralScalar(value)

private fun emitLiteralScalar(value: String) = emitScalar(value, ScalarStyle.LITERAL)
```

**Comment by charleskorn** [comment]
Thanks for the suggestion @bishwenduk029. 

Based on my reading of the [relevant section of the YAML 1.2 spec](https://yaml.org/spec/1.2.2/#literal-style), my understanding is that `|` can only be used with scalar values (eg. strings), and not lists / collection types. 

Is there a reason you want the output to be in this particular format?

**Comment by bishwenduk029** [comment]
@charleskorn , Thanks for the quick response. You are actually right. But I was just thinking like how would one represent a multi-line string in POJO. Like it can be a list of strings or string separated on some special character which can be serialized in this form. So may be some sort of an API in kaml, which allows configuring this behaviour?

As for my use case, I was trying to capture user input in POJO and then serialize this POJO into yaml file. This YAML file was then given as input to a machine learning library to process using some model.

**Comment by charleskorn** [comment]
> But I was just thinking like how would one represent a multi-line string in POJO. Like it can be a list of strings or string separated on some special character which can be serialized in this form. 

The standard way to represent a multi-line string in a POJO would be a string with new line characters (`'\n'`).

> As for my use case, I was trying to capture user input in POJO and then serialize this POJO into yaml file. This YAML file was then given as input to a machine learning library to process using some model.

kaml already handles multi-line strings correctly, and will serialize them to YAML in a format that any standard-compliant YAML parser will be able to read. Given you're using YAML to move data from one process to another without any human involvement, I'd suggest sticking to the standard format rather than trying to add something unusual.
