### ISSUE TITLE
Make decodeFromReader() public, add encodeToWriter(), encodeToStream()

### ISSUE THREAD

**Issue by Virtlink** [charleskorn/kaml#228]
### Describe the problem you'd like to solve

The methods on the `Yaml` object for reading and writing are not balanced.

### Describe the solution you'd like

I propose to make `decodeFromReader()` public, and to add `encodeToWriter()` and `encodeToStream()` as encoding methods that correspond to the decoding methods.

**Comment by charleskorn** [comment]
Thanks for the suggestion @Virtlink. That makes sense to me. Would you be interested in submitting a PR for this? Otherwise I will take a look when I get a chance.

**Comment by charleskorn** [comment]
I've added support for `encodeToStream()`.

I'm hesitant to expose `decodeFromReader()` - is there a reason why you need this over `decodeFromStream()`?

**Comment by Virtlink** [comment]
Thanks for looking into this.

> I'm hesitant to expose `decodeFromReader()` - is there a reason why you need this over `decodeFromStream()`?

The reason I proposed making `decodeFromReader()` public, is because it's the text-oriented counterpart of the byte-oriented `OutputStream`. I have had situations where I get some reader (e.g., `StringReader`, `InputStreamReader`, `PushBackReader`) and therefore know the input is textual, without having an underlying stream (if it exists at all). 

For example, I like to write tests using a `StringReader` because it exercises the same code as the I/O `Reader`, and easier than trying to wrap the string into a stream. (And in general there is neither an easy (nor efficient) way to wrap a `Reader` to an `OutputStream`.)

**Comment by charleskorn** [comment]
So, just to confirm, the main use case for `decodeFromReader()` for you is to make tests simpler? Or is there a scenario in your production code where this is valuable?

I'm not against the idea, but it does make future internal changes more difficult, and I wouldn't be able to easily expose a `encodeToWriter()` method, as the underlying YAML library I'm currently using (snakeyaml-engine) doesn't support `Writer` instances.

**Comment by Virtlink** [comment]
Yes, I tried call `decodeFromReader()` while writing tests and that's when I found it non-public. However, if it's not possible to have a `encodeToWriter` and/or it makes internal changes harder, then it might make sense to leave the method hidden. For string-based tests I can call `decodeFromString()`.

**Comment by charleskorn** [comment]
Let's stick with the stream methods for now. If there's more demand for the `Reader` / `Writer` methods in the future then I'd be happy to reconsider.
