### ISSUE TITLE
Ability to serialize/deserialize unstructured data

### ISSUE THREAD

**Issue by sjshuck** [charleskorn/kaml#231]
### Describe the problem you'd like to solve

Sometimes I need to be able to break the glass and serialize/deserialize YAML without having well-structured POJOs/KOJOs.

### Describe the solution you'd like

I'd like a canonical "vanilla" representation of YAML.  It does not have to implement all YAML features (e.g., SnakeYAML chokes on tags in its vanilla codec implementation, and I'd be fine with that behavior).  It could be a codec for `YamlNode` or `Any` or a new class created for this purpose.

This would bring it in line with other languages' YAML implementations such as Python's and Ruby's.

### Describe alternatives you've considered

A combination of SnakeYAML and Moshi.

### Additional context

My context is also multi-document YAML streams from Kubernetes, just like #54 's case.

**Comment by charleskorn** [comment]
Thanks for the report @sjshuck.

To clarify your request, are you looking for something like [kotlinx.serialization's `JsonElement`](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#parsing-to-json-element)? Or are you looking for a generic YAML parser independent of kotlinx.serialization?

If the latter, that is currently out of scope for kaml - it specifically targets kotlinx.serialization, and is not a general-purpose YAML parser for Kotlin. If you need a general-purpose YAML parser, I'd suggest using a library like snakeyaml-engine (which is what kaml uses under the hood).

**Comment by sjshuck** [comment]
Hey, thank _you_ for the response.

I think I'm looking for the former.  In addition to `JsonElement`, there's the helper method `Json.parseToJsonElement`.  I was looking for something like `Yaml.default.parseToYamlNode`.  In fact, I'd be fine with `Yaml.default.parseToJsonElement` or with a deserialization strategy for `JsonElement`, if there are concerns about making one for `YamlNode` (YAML itself being too complex for a faithful two-way generic codec, perhaps).

Regarding it being in scope, I get that snakeyaml and `kotlinx.serialization` are distinct levels of abstraction and in a sense distinct concerns.  But may I suggest that exposing the underlying repr via a codec for the repr's type is a pretty common pattern among serialization/deserialization libraries in various languages, and I always appreciate seeing it there for development, testing, and exploration.  Here, it would save me a dependency on snakeyaml.  A nice-to-have.

**Comment by charleskorn** [comment]
Right, makes sense. Would you want to be able to go in the other direction as well? (eg. convert a `YamlNode` instance to a YAML string)

If you're interested in submitting a PR, adding a `parseToYamlNode` method should be very straightforward - [`decodeFromReader` already has access to the `YamlNode`](https://github.com/charleskorn/kaml/blob/675f930eb9395d567cb0ff2ae1f37692eca381eb/src/jvmMain/kotlin/com/charleskorn/kaml/Yaml.kt#L53), so adding an alternative implementation that just stops there and returns the `YamlNode` should be very straightforward.

**Comment by sjshuck** [comment]
Great.  It's not pressing for me so I don't know exactly when I can get to
it, but I'd be happy to try to work on it if you want to keep this ticket
open for a bit.

**Comment by sjshuck** [comment]
Re: other direction, I'd have to think about it.

**Comment by sjshuck** [comment]
I'm happy with @kitterion 's solution.  Thanks for keeping this open despite me not finding time to work on it.
