### ISSUE TITLE
Support for YAML block scalars

### ISSUE THREAD

**Issue by peterfigure** [charleskorn/kaml#245]
### Describe the problem you'd like to solve

Working on a DSL for github actions, would be really nice if a multiline string or list of strings gets rendered as a block scalar, eg: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun

It makes for much easier debugging & readability than `\n` separated strings

### Describe the solution you'd like

https://yaml-multiline.info/ literal block scalars using the `|` symbol

**Comment by charleskorn** [comment]
Resolved by #247.
