### ISSUE TITLE
Add generic extension functions for `decodeFromStream`/`encodeToStream`

### ISSUE THREAD

**Issue by FloEdelmann** [charleskorn/kaml#246]
### Describe the problem you'd like to solve

For string (de)serialization, you can use the [generic `decodeFromString` / `encodeToString` extension functions](https://github.com/Kotlin/kotlinx.serialization/blob/v1.3.2/core/commonMain/src/kotlinx/serialization/SerialFormat.kt#L84-L97) without having to explicitly specify a serializer. Since kaml's `Yaml` class [implements the `StringFormat` interface](https://github.com/charleskorn/kaml/blob/0.40.0/src/jvmMain/kotlin/com/charleskorn/kaml/Yaml.kt#L38-L41), this is already possible:

```kt
val myMap = Yaml.default.decodeFromString<Map<String, Int>>(myString)
val string = Yaml.default.encodeToString(myMap)
```

When decoding from a stream, this is not possible, so the serializer has to be passed explicitly, making the code harder to read:

```kt
val myMap = Yaml.default.decodeFromStream(MapSerializer(String.serializer(), Int.serializer()), myStream)
```

### Describe the solution you'd like

Introduce extension functions that read the serializer from `serializersModule.serializer()` (just like the implementation in [kotlinx.serialization.SerialFormat](https://github.com/Kotlin/kotlinx.serialization/blob/v1.3.2/core/commonMain/src/kotlinx/serialization/SerialFormat.kt#L84-L97)):

```kt
inline fun <reified T> Yaml.decodeFromStream(stream: InputStream): T =
    decodeFromStream(serializersModule.serializer(), stream)

inline fun <reified T> Yaml.encodeToStream(value: T, stream: OutputStream) =
    encodeToStream(serializersModule.serializer(), value, stream)
```

**Comment by charleskorn** [comment]
Makes sense to me. Would you be interested in submitting a PR with those changes @FloEdelmann?

**Comment by FloEdelmann** [comment]
Done: #248
