### ISSUE TITLE
Kotlin 1.4 support

### ISSUE THREAD

**Issue by 2beaucoup** [charleskorn/kaml#26]
Would you accept a PR that upgrades to Kotlin 1.4?

We're upgrading to 1.4.0-rc and getting
```
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/serialization/modules/EmptyModule;
	at com.charleskorn.kaml.Yaml.<init>(Yaml.kt:33)
	at com.charleskorn.kaml.Yaml.<clinit>(Yaml.kt:58)
```
with `org.jetbrains.kotlin:kotlin-serialization:1.4.0-rc` and `org.jetbrains.kotlinx:kotlinx-serialization-runtime:1.0-M1-1.4.0-rc`.

Maybe 0.18.x could stay compatible with Kotlin 1.3.

**Comment by charleskorn** [comment]
I've just added support for Kotlin 1.4.0 and kotlinx.serialization 1.0.0-RC as part of 938d250f59def1079c774b536a7cd3bce209e3d4 and I'll release it shortly.

**Comment by charleskorn** [comment]
But to answer your original question - in general, yes, I would always be interested in PRs like that :)
