### ISSUE TITLE
Option to not serialize default values only if they are `null`

### ISSUE THREAD

**Issue by Vampire** [charleskorn/kaml#318]
### Describe the problem you'd like to solve

I'd like to be able to tell Kaml to serialize default values, but only if they are non-null.
Currently I only see the option to either serialize all default values or none of them.

### Describe the solution you'd like

An option to enable such a mode.

**Comment by charleskorn** [comment]
Unfortunately this is not supported by kotlinx.serialization (see #8), so kaml can't support it.

I had a quick look through the open feature requests for kotlinx.serialization and I can't find anything related to this, so it might be worth opening an issue over in their repo and explaining your use case.

**Comment by mroche89** [comment]
A workaround you can use would be to apply the annotation `@EncodeDefault(EncodeDefault.Mode.NEVER)` to the individual property whose default value you'd like omitted. This way you can selectively apply it to properties that default to `null`

**Comment by Vampire** [comment]
Ah, thanks @mroche89, that's perfectly fine for me.
Actually the othe way around, having encode defaults `true` and then annotating the one special with `@EncodeDefault`. :-)
