### ISSUE TITLE
Polymorphism Type Property Required

### ISSUE THREAD

**Issue by Timmetjeee** [charleskorn/kaml#364]
### Describe the problem you'd like to solve

When using a default deserializer for a polymorphic class, it will not be used if the "type" property is not defined. The json implementation did use the default deserializer.

```kotlin
fun main() {
    val yaml = Yaml(
        serializersModule = SerializersModule {
            polymorphic(SuperClass::class) {
                subclass(SubClassB::class)
                defaultDeserializer { SubClassA.serializer() }
            }
        },
        configuration = YamlConfiguration(
            strictMode = false,
            polymorphismStyle = PolymorphismStyle.Property
        )
    )

    println(
        yaml.decodeFromString<SuperClass>(
            """
            valueA: "Test"
        """.trimIndent()
        )
    ) // Throws error saying property "type" is not defined.
}


interface SuperClass

@Serializable
data class SubClassA(val valueA: String) : SuperClass

@Serializable
data class SubClassB(val valueB: Int) : SuperClass
```

### Describe the solution you'd like

When strictMode is set to false, it should use the default deserializer if it is specified when the "type" property is not defined.

### Describe alternatives you've considered

I tried using other yaml implementations but they were lacking a lot of features.

**Comment by charleskorn** [comment]
Thanks for the report @Timmetjeee. This isn't currently supported by kaml, but it shouldn't be too hard to add. Would you be interested in submitting a PR to add this?

[`createPolymorphicMapDeserializer()`](https://github.com/charleskorn/kaml/blob/047820a1750a8b10c9267a290ed391471145479c/src/commonMain/kotlin/com/charleskorn/kaml/YamlInput.kt#L77) is likely the place that needs some changes. I'd suggest looking at what kotlinx-serialization's built-in JSON parser does for further hints on what needs to be done.
