### ISSUE TITLE
Exception Location information is wrong

### ISSUE THREAD

**Issue by Vampire** [charleskorn/kaml#37]
I just got a parse error at `Exception Location: Location(line=243, column=23)` saying `Value for 'distribution1' is invalid: Expected a string, but got a map`.
But in my input file at 243:23 there is no `distribution1` key.
The earliest is at line 557.

Actually at 243:23 I define an anchor for a map.
And then further down e. g. at 557 for `distribution1` I use that anchor.
So the line information is showing the referenced to line instead of the referencing line which makes it a bit harder to find the actual problem, as you don't know which referencing line causes a parsing error.

**Comment by charleskorn** [comment]
Hey @Vampire, thanks for the feedback. Are you able to share a simple sample YAML file that demonstrates the problem? It  would be helpful to be able to reproduce the issue you're seeing so that I can confirm that I've fixed the problem.

**Comment by Vampire** [comment]
Sure:
**input file:**
```yaml
bar:
    - &baz
      bam: boo

foo: *baz
```
**DAO:**
```kt
@Serializable
data class Foo(
        val bar: List<Map<String, String>>,
        val foo: String
)
```
**Result:**
```
Exception Location: Location(line=2, column=7)
Value for 'foo' is invalid: Expected a string, but got a map
```

----

2:7 is the `&` character

**Comment by charleskorn** [comment]
Just to keep you updated - this is not straightforward to fix, so I'm not going to be able to fix it soon. I'll keep the issue open until I have a chance to take a look at this.

**Comment by charleskorn** [comment]
This has been fixed, and will be part of the next release.

Exceptions now have the concept of a path, which shows the path taken to get to the location of the error. For example `foo.bar`, or in the case of the error above, `foo->&baz`. Exception messages now include the path in `toString()`, and for more advanced use cases, you can inspect the path property to see the location (line and column) of each segment of the path.
