### ISSUE TITLE
PolymorphismStyle.None

### ISSUE THREAD

**Issue by mgroth0** [charleskorn/kaml#378]
### Describe the problem you'd like to solve

I would like to serialize classes belonging to a polymorphic hierarchy as if they were not. I understand this means they can no longer be correctly deserialized, so I understand why there might be hesitation to support such a feature. Maybe it can be part of a separate API.

### Describe the solution you'd like

allowing `PolymorphismStyle.None`, which would simply do nothing when a class is polymorphic, would work for me. Alternatively, having a separate method to serialize objects without considering if they are polymorphic would be ok. 

### Describe alternatives you've considered

I am using `PolymorphismStyle.Tag` and trying to remove these tags by searching the string.

### Additional context

I may be serializing an object which will be deserialized in another program altogether, and that other program does not need the polymorphic tags.

**Comment by charleskorn** [comment]
Thanks for the suggestion @mgroth0. If you're interested in submitting a PR with this change, I'd be happy to accept it.

**Comment by ZacSweers** [comment]
I'll take a look at a PR

**Comment by ZacSweers** [comment]
#494
