### ISSUE TITLE
Add Yaml Naming Strategies

### ISSUE THREAD

**Issue by russellbanks** [charleskorn/kaml#398]
### Describe the problem you'd like to solve

There is no naming strategy implementation, so `@SerialName` has to be applied to every variable in a data class:

```kotlin
@SerialName("PackageIdentifier") val packageIdentifier: String,
@SerialName("PackageVersion") val packageVersion: String
```

### Describe the solution you'd like

A YamlNamingStrategy in the YamlConfiguration.

```kotlin
configuration = YamlConfiguration(
    yamlNamingStrategy = YamlNamingStrategy.PascalCase // CamelCase, SnakeCase, etc
)
```

### Describe alternatives you've considered

`@SerialName` on every variable

### Additional context

KotlinX Serialization recently added Json naming strategies in [1.5.0](https://github.com/Kotlin/kotlinx.serialization/releases/tag/v1.5.0-RC):

> A long-awaited feature (https://github.com/Kotlin/kotlinx.serialization/issues/33) is available in this release.
A new interface, JsonNamingStrategy and Json configuration property namingStrategy allow defining a transformation that is applied to all properties' names serialized by a Json instance.
There's also a predefined implementation for the most common use case: Json { namingStrategy = JsonNamingStrategy.SnakeCase }.
Check out the https://github.com/Kotlin/kotlinx.serialization/pull/2111 for more details and documentation.

```kotlin
Json {
    namingStrategy = JsonNamingStrategy.SnakeCase // Predefined
}
```

```kotlin
Json {
    namingStrategy = JsonNamingStrategy { descriptor: SerialDescriptor, elementIndex: Int, serialName: String ->
        // Able to define custom naming strategy
    }
}
```
https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-json/kotlinx.serialization.json/-json-naming-strategy

**Comment by charleskorn** [comment]
I don't have time to work on this myself, but I'd gladly review a PR for this if you're interested in putting one together.
