### ISSUE TITLE
Support Polymorphic serialization

### ISSUE THREAD

**Issue by frzme** [charleskorn/kaml#4]
It would be nice if Polymorphic (de)serialization was supported in the same way it is for JSON.

(see https://medium.com/@andreclassen1337/goodbye-runtimetypeadapterfactory-polymorphic-serialization-using-kotlinx-serialization-46a8cec36fdc )

**Comment by charleskorn** [comment]
Hi @frzme, thanks for the suggestion!

I don't have capacity to add this in the short term, so if you're keen, I'm happy to provide some pointers and review a PR as you go. I'm imagining this would use YAML's local tags syntax (`!square` / `!circle`) to indicate the type - https://camel.readthedocs.io/en/latest/yamlref.html#tags has a good explanation of this. Was that what you had in mind, or were you thinking of something else?

**Comment by frzme** [comment]
Hi @charleskorn I was not aware of this feature and thus was thinking of basically the same as in json - but if it yaml has native support for it it sounds great to use it.

Unfortunatly I most likely also won't have capacity to work on it anytime soon.

**Comment by charleskorn** [comment]
This has been resolved with #7 and will be part of the next release.
