### ISSUE TITLE
Avoid using data classes in Kaml's code

### ISSUE THREAD

**Issue by russellbanks** [charleskorn/kaml#422]
### Describe the problem you'd like to solve

Part of Kotlin's (recent) [don't do recommendations](https://kotlinlang.org/docs/jvm-api-guidelines-backward-compatibility.html) for public APIs is to not use data classes.

https://kotlinlang.org/docs/jvm-api-guidelines-backward-compatibility.html#don-t-use-data-classes-in-api:

> [Data classes](https://kotlinlang.org/docs/data-classes.html) are tempting to use because they are short, concise, and have some functionality out of the box. However, due to some specifics of how data classes work, it's better not to use them in library APIs. Almost any change makes the API not backward compatible.

### Describe the solution you'd like

Replace data classes with regular classes and generate equals, hashCode and toString where needed.

I can make a PR for this change if you'd like

**Comment by charleskorn** [comment]
Given kaml has not yet reached v1.0, I'm OK with breaking backwards compatibility and binary compatibility.

**Comment by russellbanks** [comment]
> Given kaml has not yet reached v1.0, I'm OK with breaking backwards compatibility and binary compatibility if needed.

To clarify, is this okay with breaking compatibility by replacing data classes with normal classes or keeping data classes as they are

**Comment by charleskorn** [comment]
Keeping data classes as they are (for now at least)
