### ISSUE TITLE
Allow nullable yaml value using default value to setup

### ISSUE THREAD

**Issue by fankes** [charleskorn/kaml#427]
### Describe the problem you'd like to solve

Yaml like this:

```yaml
fruit:
  apple:
  banana:
    eat: true
```

Serialization class like this:

```kotlin
@Serializable
data class Test(
    var fruit: Fruit = Fruit()
)
```

```kotlin
@Serializable
data class Fruit(
    var apple: Apple = Apple(),
    var banana: Banana = Banana()
)
```

```kotlin
@Serializable
data class Apple(
    var eat: Boolean = true
)
```

```kotlin
@Serializable
data class Banana(
    var eat: Boolean = true
)
```

Currently, parsing to serialization throws an exception:

```
com.charleskorn.kaml.InvalidPropertyValueException at fruit.apple on line 2, column 9: Value for 'apple' is invalid: Unexpected null or empty value for non-null field.
```

But `apple` has a default value `Apple()`.

If I do this following, the default value also cannot be applied to, also got null value.

This will not know whether the key exists on the node.

```kotlin
@Serializable
data class Fruit(
    var apple: Apple? = Apple(),
    ...
)
```

### Describe the solution you'd like

Allow nullable yaml value using default value to setup, like the title said.

If possible, this feature can be added to the configuration options.

### Describe alternatives you've considered

Using this way:

```kotlin
@Serializable
data class Fruit(
    var apple: Apple?
    ...
)
```

And using this way to read the default value:

```kotlin
val fruit = // Assume it has been parsed to Fruit() by Yaml
val apple = fruit.apple ?: Apple()
```

But also will not know whether the key exists on the node.

### Additional context

like #61

**Comment by charleskorn** [comment]
What happens if you use this YAML input?

```yaml
fruit:
  banana:
    eat: true
```

**Comment by fankes** [comment]
I want to mark the `apple` exist, but let the value null

**Comment by charleskorn** [comment]
Unfortunately that's not possible. Specifying `apple:` in YAML means "set `apple` to `null`".

**Comment by fankes** [comment]
I want to achieve this:

```kotlin
var apple: Apple? = Apple()
```

Create an option to allow this way to using `apple` 's default value to parse it if null.

**Comment by fankes** [comment]
Because whether I add a node like `apple:` or not, I cannot know whether it is added in the parsed entity object.

**Comment by charleskorn** [comment]
> Because whether I add a node like `apple:` or not, I cannot know whether it is added in the parsed entity object.

If you require this level of knowledge of the structure of the YAML document, then I'd recommend using something like SnakeYAML instead. Kaml is intended to make it easy to use YAML with kotlinx.serialization.

**Comment by fankes** [comment]
Right, I know it about this :(
But there are some easilly way to get the node exist? without load again from a map.

**Comment by charleskorn** [comment]
> Right, I know it about this :( But are there some easilly way to get the node exist? without load again from a map.

You could implement a custom serializer for the `Fruit` type that would be able to check if the `apple` key is present.

**Comment by fankes** [comment]
Thanks a lot, I will try it.

Sorry, I'm not very familiar with `kotlinx.serializatio`, please forgive me.

**Comment by fankes** [comment]
It may be that I want to use a custom Yaml, which cannot meet my needs, thank you again.
