### ISSUE TITLE
Number are not parsed according YML 1.2 specification 

### ISSUE THREAD

**Issue by vadim-hleif** [charleskorn/kaml#484]
### Describe the bug

input:
```yml
key: 42_000
```

exception:
`Value '42_000' is not a valid long value.`

spec says:
`Any “_” characters in the number are ignored, allowing a readable representation of large values.`

### Steps to reproduce

1. Create any model with number field (e.g. Int or Long)
2. try to decode model from string

### Expected behaviour

1. YML decoded correctly, _ just ignored

### Actual behaviour

exception:
`Value '42_000' is not a valid long value.`

### Version information

```plain text
0.55.0
```

### Any other information

YML specification is confusing. 
In the root of 1.2 it's not directly said that underscore is allowed, but it has reference in 10.4 part of subdocument from 1.1 version, where it's said that's underscore is allowed. 

https://yaml.org/spec/1.2.0/#id2604885 -> https://yaml.org/type/int.html

Found similar conversation here https://github.com/symfony/symfony/issues/27120

**Comment by charleskorn** [comment]
Thanks for the bug report @vadim-hleif.

On https://yaml.org/type/int.html, under "status", it says: "This specification is a draft". Until this is an accepted spec, I'd like to stick to what's in the YAML 1.2 spec.

**Comment by vadim-hleif** [comment]
Sorry, you are right, looks like it's not part of 1.2 spec, it's 1.1

It's confusing because a lot of libraries implemented support of it and refer to the document.
