### ISSUE TITLE
No Common Constructor in com.charleskorn.kaml.Yaml

### ISSUE THREAD

**Issue by mgroth0** [charleskorn/kaml#502]
### Describe the bug

I think that expect classes require `()` to be explicitly written after the class name like so in order to generate a common constructor:

```kotlin
public expect class Yaml() : StringFormat {
```

Currently the `()` is absent, and the consctuor is unresolved in a common module for me. I am forced to create an expect function and construct the class in each target.

### Reproduction repo

```kotlin
import com.charleskorn.kaml.Yaml

fun main() {
    Yaml(Yaml.default.configuration)
}
```

### Steps to reproduce

1. Run the code above in a jvm or js module and it will work.
2. Put the code in a common module, and it will not compile.

### Expected behaviour

Given that the `Yaml` class is constructed the same way for each target, it can have a common constructor.

### Actual behaviour

No comon constructor.

### Version information

```plain text
0.57.0
```

### Any other information

Reference to a discussion on this topic: https://youtrack.jetbrains.com/issue/KTIJ-19069/MPP-IDE-only-error-RESOLUTIONTOCLASSIFIER-Expected-class-has-no-default-constructor-for-reference-to-implicit-default

**Comment by charleskorn** [comment]
Thanks for the bug report @mgroth0! Would you be interested in opening a PR to fix this?

**Comment by charleskorn** [comment]
This has been resolved in https://github.com/charleskorn/kaml/commit/77d85ee95da565273251e9fb3933c72ad38801df and will be part of the next release.
