### ISSUE TITLE
For polymorphic (de)serialization, use default serializer if `type` property is ommited.

### ISSUE THREAD

**Issue by paloliska** [charleskorn/kaml#518]
### Describe the problem you'd like to solve

If there is polymorphic default serializer, I would like to use it not only for unknown classes, but also, when class is not defined.
For example, if property style polymorphism is defined and `type` property is not defined in input yaml.

### Describe the solution you'd like

I would like to save some lines in source yaml file.

**Comment by charleskorn** [comment]
Thanks for the issue @paloliska. Is this supported by kotlinx.serialization's JSON format? I suspect what you're suggesting isn't supported by kotlinx.serialization, unless I've missed something.
