### ISSUE TITLE
SingleLineStringStyle.Plain quotes polymorphic type

### ISSUE THREAD

**Issue by PaulWoitaschek** [charleskorn/kaml#520]
### Describe the bug

SingleLineStringStyle.Plain quotes polymorphic types

### Steps to reproduce

```kotlin
fun sample() {
  val yaml = Yaml(
    configuration = YamlConfiguration(
      polymorphismStyle = PolymorphismStyle.Property,
      singleLineStringStyle = SingleLineStringStyle.Plain,
    ),
  )
  println(
      yaml.encodeToString(Something.serializer(), Something.A("Alice")),
  )
}
```

### Expected behaviour

This should have the type unqouted

### Actual behaviour

It's quoted:

```yaml
type: "a"
name: Alice
```

### Version information

```plain text
0.57.0
```

**Comment by charleskorn** [comment]
Thanks for the bug report @PaulWoitaschek! I'm low on free time at the moment and so won't be able to fix this for a while - would you be interested in submitting a PR to fix it?
