### ISSUE TITLE
Support in SnakeYAML Engine

### ISSUE THREAD

**Issue by asomov** [charleskorn/kaml#53]
Hi, 
thank you for the attempt to support YAML in Kotlin.
Is there anything missing in SnakeYAML Engine you would like to add or change ?

I am a SnakeYAML developer.
Cheers,
Andrey

**Comment by charleskorn** [comment]
Hi @asomov, thanks for reaching out! At the moment, I don't think there's anything I would want to add or change to SnakeYAML, but I'll let you know if I think of anything.
