### ISSUE TITLE
Support FlowStyle.Flow to minify yaml

### ISSUE THREAD

**Issue by HalfLegend** [charleskorn/kaml#577]
### Describe the problem you'd like to solve

Kaml only support FlowStyle.Flow in sequence type.
All other cases are FlowStyle.Block which contains a lot of indients which is space comsuming.
I want to minify my yaml with FlowStyle.Flow

### Describe the solution you'd like

Add an "FlowStyle" option to YamlConfiguration and pass the config directly to DumpSettings of the Emitter provided in snakeymal.engine

**Comment by charleskorn** [comment]
Thanks for the suggestion @HalfLegend! If you're open to submitting a PR for this, I'd be happy to add this.
