### ISSUE TITLE
Missing release notes for 0.61.1

### ISSUE THREAD

**Issue by westnordost** [charleskorn/kaml#600]
### Describe the problem you'd like to solve

On Maven Central, there is a new artifact 0.61.0, but I don't see any mention of it here and also no release notes.

### Describe the solution you'd like

Release notes are important to see if any changes should be made when upgrading the dependency.
Since the version number is still in the 0.x range, I expect that a minor version change might also include possibly breaking API changes.

**Comment by charleskorn** [comment]
Thanks for letting me know about this, and sorry for the confusion - I'd drafted the release notes but not published them. They've now been published.
