### ISSUE TITLE
Support all Tier 2 Multiplatform targets

### ISSUE THREAD

**Issue by rbraeunlich** [charleskorn/kaml#628]
### Describe the problem you'd like to solve

Hi everyone,
I was looking at the supported multiplatform targets and saw that out of tier 2 those three are currently supported:
```
    linuxX64()
    linuxArm64()
    iosArm64()
```
whereas for full tier 2 compatibility the list should look like this:
```
    linuxX64()
    linuxArm64()
    watchosSimulatorArm64()
    watchosX64()
    watchosArm32()
    watchosArm64()
    tvosSimulatorArm64()
    tvosX64()
    tvosArm64()
    iosArm64()
```
Snakeyaml-KMP supports all of the above: https://github.com/krzema12/snakeyaml-engine-kmp/blob/main/buildSrc/src/main/kotlin/buildsrc/conventions/lang/kotlin-multiplatform.gradle.kts#L68

### Describe the solution you'd like

Therefore, I was wondering if it would be possible to extend the tier 2 support. Since the missing watchos and tvos are also Apple based and ios is already supported the change might be small. Hopefully, just extending the list and adjusting the GitHub action.

**Comment by charleskorn** [comment]
This makes sense to me, feel free to open a PR for this.

**Comment by carlonzo** [comment]
issue can be closed now that the pr is merged
