### ISSUE TITLE
Please provide a description how to use

### ISSUE THREAD

**Issue by dodalovic** [charleskorn/kaml#67]
Hi, I'm trying to use the tool you provided, but without luck so far. 

What do I need to configure in my Gradle project?

Thank you!

**Comment by charleskorn** [comment]
Hi @dodalovic, [the readme](https://github.com/charleskorn/kaml#referencing-kaml) contains this section:


> ## Referencing kaml
> 
> Add the following to your Gradle build script:
> 
> ```kotlin
> implementation("com.charleskorn.kaml:kaml:<version number here>")
> ```
> 
> Check the [releases page](https://github.com/charleskorn/kaml/releases) for the latest release information,
> and the [Maven Central page](https://search.maven.org/artifact/com.charleskorn.kaml/kaml) for examples of how
> to reference the library in other build systems.

Is this not clear? I'm happy to flesh it out further if it is not clear enough.

**Comment by dodalovic** [comment]
Thanks, I was able to get it to work... Maybe just putting somewhere info what are the dependencies from `kotlinx-serialization`

Thanks

**Comment by charleskorn** [comment]
Thanks for the feedback - I've just added more details to the readme. Please let me know if you think there's anything else I can do to make it clearer.
