### ISSUE TITLE
How to not stringify property with null value ?

### ISSUE THREAD

**Issue by Will3333** [charleskorn/kaml#8]
Hello,

I have several classes with nullable properties. Is there a way to not stringify a property when it has a null value ?

**Comment by charleskorn** [comment]
Hi @Will3333! If the default value for those properties is `null`, you can set `encodeDefaults` to `false` and then null values will be omitted.

**Comment by Will3333** [comment]
> Hi @Will3333! If the default value for those properties is `null`, you can set `encodeDefaults` to `false` and then null values will be omitted.

With encodeDefaults to false, all properties with default values will be omitted, not only null value.
Sorry to bother you, this point seems to be more of related to kotlinx.serialization than kaml.

**Comment by charleskorn** [comment]
Ah, I see your question now. There's no built-in way to do this at the moment, and I don't think it's possible to only encode non-null default values with what kotlinx.serialization supports - https://github.com/charleskorn/kaml/blob/master/src/main/kotlin/com/charleskorn/kaml/YamlOutput.kt#L54 is where we have to make the decision and we don't know what the default value is at that point. 

You might need to submit an issue with the kotlinx.serialization team to ask them to add support for this first.

**Comment by rekire** [comment]
Is there an update? I would like to avoid rendering null values?

**Comment by charleskorn** [comment]
Hi @rekire, this is currently not supported by kotlinx.serialization out of the box, except if you want to exclude writing all default values.

If you want to exclude only null default values, you'll need to provide your own serializer that selectively includes the field depending on whether it is null or not.

**Comment by BlackBaroness** [comment]
Hello there! Looks like it was fixed in `kotlinx.serialization`: https://github.com/Kotlin/kotlinx.serialization/issues/195 with `Json { explicitNulls = false }`
Can we see the same thing in kaml as well?

It's a really important feature since the object may have a lot of optional fields, so I believe many users would want to see kaml treat missing nullable fields as nulls and not fill it with nulls explicitly.
