### ISSUE TITLE
Support for comments

### ISSUE THREAD

**Issue by asomov** [charleskorn/kaml#87]
Hi, there is [a pending PR in SnakeYAML Engine](https://bitbucket.org/asomov/snakeyaml-engine/pull-requests/1) with implementation for parsing and serializing comments.
Do you think this project might benefit from this feature ?

Cheers,
Andrey

**Comment by charleskorn** [comment]
Hi @asomov, I'm not sure it would be so helpful for this project - kotlinx.serialization doesn't have support for comments, so I'm not sure how kaml could surface them. Was there a particular implementation you had in mind?

**Comment by asomov** [comment]
I know that in Jackson they ask a lot to support comments even though it should be even more complex.
I just wanted to know if there is a use case in kaml
